### PR TITLE
Add 'documentation' to Cargo.toml

### PR DESCRIPTION
**Pull request by rusty-snake**
This makes crates.io adding a link to it.

### CODE REVIEW

**Comment by Nugine** [comment]
<https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field>

I think it's better to leave it default.

**Comment by rusty-snake** [comment]
In theory this is better, right. However I don't see a Documentation link the to Repository on https://crates.io/crates/rlimit only the small one from the badgen.

**Comment by Nugine** [comment]
Screenshot_20201210_234609

Here it is.

**Comment by rusty-snake** [comment]
Found the issue: If documentation is not set, https://crates.io/api/v1/crates/rlimit contains `documentation: null` and a extra requests to docs.rs is done in order to see if there is a documentation for the crate. If this request is successful, the link is added (with some delay). This second request was blocked.

**Pull request closed without merging**
